### ISSUE TITLE
Support additional file objects - symlinks

### ISSUE THREAD

**Issue by rbtcollins** [rbtcollins/fs_at#10]

**Comment by rbtcollins** [comment]
@ChrisDenton suggests  

```
As to your question, you can create a symbolic link by creating a file or directory in the ordinary way then using DeviceIoControl with FSCTL_SET_REPARSE_POINT on the handle. There's some code in the standard library for creating juncture points but not for symlinks, which use a different data structure. https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/library/std/src/sys/windows/fs.rs#L1329
```

**Comment by ChrisDenton** [comment]
To expand on that a bit, in Windows a symlink (or some other types of links) are just ordinary files or directories with some "reparse" metadata attached. These are called "reparse points". So long as a file or directory remains empty you can switch between it being a link and it not being a link by adding or removing the metadata.

You can see what that metadata looks like here: [REPARSE_DATA_BUFFER](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_reparse_data_buffer). That particular structure uses unions but it's basically just a standard reparse header followed by a data structure whose type depends on the [reparse tag](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c8e77b37-3909-4fe6-a4ea-2b9d423b1ee4) used in the header.

This metadata can be set using the [DeviceIoControl](https://docs.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol) function with the control code set to [FSCTL_SET_REPARSE_POINT](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/fsctl-set-reparse-point).

We do have some code in the standard library that makes use of reparse data. Notably [`read_link`](https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/library/std/src/sys/windows/fs.rs#L483) but also for [setting juncture points](https://github.com/rust-lang/rust/blob/1f5d8d49eb6111931091f700d07518cd2b80bc18/library/std/src/sys/windows/fs.rs#L1316) (though this latter is only use for testing purposes so may not be reliable for production use).

**Comment by sourcefrog** [comment]
On Unix, as well as `readlinkat` it would be nice to have `lstatat` too. 

As we discussed elsewhere on Linux and some others you can potentially open the symlink's path with `O_PATH` and then read and stat it.

**Comment by rbtcollins** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/b41f1cbf-10df-4a47-98d4-1c52a833d913 has some good data

**Comment by rbtcollins** [comment]
And https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/a8da655c-8b0b-415a-b726-16dc33fa5827
